services:
  - type: web
    name: faga-backend-engine
    env: docker
    plan: free
    region: frankfurt

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: DB_CONNECTION
        value: pgsql